// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type SgpEvent struct {
	SessionID string
	Seq       int64
	EventJson json.RawMessage
	CreatedAt pgtype.Timestamptz
}

type SgpNode struct {
	ID        string
	SessionID string
	Role      string
	ParentIds []string
	SynthFrom []string
}
