// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireSessionLock = `-- name: AcquireSessionLock :exec
SELECT pg_advisory_xact_lock(hashtext($1::text))
`

func (q *Queries) AcquireSessionLock(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, acquireSessionLock, sessionID)
	return err
}

const countNodesBySession = `-- name: CountNodesBySession :one
SELECT count(*)::int
FROM sgp_events
WHERE session_id = $1
  AND event_json ? 'node'
`

func (q *Queries) CountNodesBySession(ctx context.Context, sessionID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNodesBySession, sessionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const fetchEventBySeq = `-- name: FetchEventBySeq :one
SELECT event_json
FROM sgp_events
WHERE session_id = $1
  AND seq = $2
`

type FetchEventBySeqParams struct {
	SessionID string
	Seq       int64
}

func (q *Queries) FetchEventBySeq(ctx context.Context, arg FetchEventBySeqParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, fetchEventBySeq, arg.SessionID, arg.Seq)
	var event_json json.RawMessage
	err := row.Scan(&event_json)
	return event_json, err
}

const fetchNodesByIDs = `-- name: FetchNodesByIDs :many
SELECT event_json
FROM sgp_events
WHERE event_json->'node'->>'id' = ANY($1::text[])
ORDER BY seq
`

func (q *Queries) FetchNodesByIDs(ctx context.Context, ids []string) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, fetchNodesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var event_json json.RawMessage
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesBySession = `-- name: GetEdgesBySession :many
SELECT sgp_nodes.id AS from_id, unnest(parent_ids) AS to_id, 'parent'::text AS kind
FROM sgp_nodes
WHERE sgp_nodes.session_id = $1
  AND array_length(parent_ids, 1) > 0
UNION ALL
SELECT sgp_nodes.id AS from_id, unnest(synth_from) AS to_id, 'synthesized_from'::text AS kind
FROM sgp_nodes
WHERE sgp_nodes.session_id = $1
  AND array_length(synth_from, 1) > 0
`

type GetEdgesBySessionRow struct {
	FromID string
	ToID   interface{}
	Kind   string
}

func (q *Queries) GetEdgesBySession(ctx context.Context, sessionID string) ([]GetEdgesBySessionRow, error) {
	rows, err := q.db.Query(ctx, getEdgesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEdgesBySessionRow{}
	for rows.Next() {
		var i GetEdgesBySessionRow
		if err := rows.Scan(&i.FromID, &i.ToID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLineage = `-- name: GetLineage :many
WITH RECURSIVE lineage(id, parent_ids, depth) AS (
    SELECT sgp_nodes.id, sgp_nodes.parent_ids, 0
    FROM sgp_nodes
    WHERE sgp_nodes.id = $1
    UNION ALL
    SELECT n.id, n.parent_ids, l.depth + 1
    FROM sgp_nodes n
    INNER JOIN lineage l ON n.id = l.parent_ids[1]
    WHERE array_length(l.parent_ids, 1) > 0
)
SELECT id FROM lineage ORDER BY depth DESC
`

func (q *Queries) GetLineage(ctx context.Context, nodeID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getLineage, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNodesBySession = `-- name: GetNodesBySession :many
SELECT event_json
FROM sgp_events
WHERE session_id = $1
  AND event_json ? 'node'
ORDER BY seq
`

func (q *Queries) GetNodesBySession(ctx context.Context, sessionID string) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, getNodesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var event_json json.RawMessage
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO sgp_events (session_id, event_json)
VALUES ($1, $2)
RETURNING seq
`

type InsertEventParams struct {
	SessionID string
	EventJson json.RawMessage
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent, arg.SessionID, arg.EventJson)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const insertNode = `-- name: InsertNode :exec
INSERT INTO sgp_nodes (id, session_id, role, parent_ids, synth_from)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO NOTHING
`

type InsertNodeParams struct {
	ID        string
	SessionID string
	Role      string
	ParentIds []string
	SynthFrom []string
}

func (q *Queries) InsertNode(ctx context.Context, arg InsertNodeParams) error {
	_, err := q.db.Exec(ctx, insertNode,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.ParentIds,
		arg.SynthFrom,
	)
	return err
}

const listSessionsAfter = `-- name: ListSessionsAfter :many
WITH first_events AS (
    SELECT DISTINCT ON (session_id) session_id, event_json, created_at
    FROM sgp_events
    ORDER BY session_id, seq
)
SELECT session_id, event_json, created_at
FROM first_events
WHERE session_id > $1
ORDER BY session_id
LIMIT $2
`

type ListSessionsAfterParams struct {
	PageToken string
	Lim       int32
}

type ListSessionsAfterRow struct {
	SessionID string
	EventJson json.RawMessage
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListSessionsAfter(ctx context.Context, arg ListSessionsAfterParams) ([]ListSessionsAfterRow, error) {
	rows, err := q.db.Query(ctx, listSessionsAfter, arg.PageToken, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsAfterRow{}
	for rows.Next() {
		var i ListSessionsAfterRow
		if err := rows.Scan(&i.SessionID, &i.EventJson, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsFirst = `-- name: ListSessionsFirst :many
SELECT DISTINCT ON (session_id) session_id, event_json, created_at
FROM sgp_events
ORDER BY session_id, seq
LIMIT $1
`

type ListSessionsFirstRow struct {
	SessionID string
	EventJson json.RawMessage
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListSessionsFirst(ctx context.Context, lim int32) ([]ListSessionsFirstRow, error) {
	rows, err := q.db.Query(ctx, listSessionsFirst, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsFirstRow{}
	for rows.Next() {
		var i ListSessionsFirstRow
		if err := rows.Scan(&i.SessionID, &i.EventJson, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventsBySession = `-- name: LoadEventsBySession :many
SELECT event_json
FROM sgp_events
WHERE session_id = $1
ORDER BY seq
`

func (q *Queries) LoadEventsBySession(ctx context.Context, sessionID string) ([]json.RawMessage, error) {
	rows, err := q.db.Query(ctx, loadEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []json.RawMessage{}
	for rows.Next() {
		var event_json json.RawMessage
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loadEventsWithSeq = `-- name: LoadEventsWithSeq :many
SELECT seq, event_json
FROM sgp_events
WHERE session_id = $1
ORDER BY seq
`

type LoadEventsWithSeqRow struct {
	Seq       int64
	EventJson json.RawMessage
}

func (q *Queries) LoadEventsWithSeq(ctx context.Context, sessionID string) ([]LoadEventsWithSeqRow, error) {
	rows, err := q.db.Query(ctx, loadEventsWithSeq, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoadEventsWithSeqRow{}
	for rows.Next() {
		var i LoadEventsWithSeqRow
		if err := rows.Scan(&i.Seq, &i.EventJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notifySession = `-- name: NotifySession :exec
SELECT pg_notify($1, $2)
`

type NotifySessionParams struct {
	Channel string
	Payload string
}

func (q *Queries) NotifySession(ctx context.Context, arg NotifySessionParams) error {
	_, err := q.db.Exec(ctx, notifySession, arg.Channel, arg.Payload)
	return err
}
